export const genres = [
  "Fantasy",
  "Science Fiction",
  "Mystery",
  "Thriller",
  "Romance",
  "Horror",
  "Adventure",
  "Historical Fiction",
  "Comedy",
  "Drama",
  "Dystopian",
  "Fairy Tale",
  "Western",
  "Steampunk",
  "Post-Apocalyptic",
  "Superhero",
  "Mythology",
  "Slice of Life",
  "Crime",
  "Paranormal",
  "Epic",
  "Dark Fantasy",
  "Urban Fantasy",
  "Space Opera",
  "Magical Realism",
];
